import random

words = ["accident du travail", 
"agence pour l'emploi", 
"allocation chômage",
"ancienneté (à l')",
"annonces (petites)",
"augmentation de salaire",
"avancement",
"avantages en nature",
"base (à la)",
"boulots (petits)",
"bulletin de salaire",
"cadre (jeune)",
"cadre moyen",
"cadre supérieur", #14
"candidat (à un emploi)",
"candidature",
"candidature (poser sa)",
"carrière",
"chef du personnel",
"chômage",
"chômeurs (les)",
"congé",
"congé (être en)",
"congé de maternité",
"congés payés",
"contrat",
"contrat à durée déterminée",
"contremaître",
"curriculum vitae",
"dégraissage",
"demandeur d'emploi",
"démission",
"diplômes",
"direction",
"embaucher",
"emploi (l')",
"employé (un)",
"employeur",
"entreprise",
"entretien d'embauche",
"égalité des chances",
"équipe",
"essai (à l')",
"formation professionnelle", #44
"formation sur le tas",
"former (se)",
"gagner (argent)",
"grève",
"grève (se mettre en)",
"gréviste",
"heures supplémentaires",
"horaire de travail",
"indemnité",
"indemnité de chômage",
"jour de congé",
"jour de fête légal",
"jour ouvrable",
"licencié (être)",
"licenciement",
"licenciement pour cause de chômage technique",
"main d'oeuvre",
"maladie professionnelle",
"mobilité",
"négocier",
"non qualifié",
"norme de sécurité",
"ouvrier non qualifié",
"ouvrier qualifié",
"ouvrier spécialisé",
"participation",
"patron",
"patronat",
"pause",
"pension",
"permis de travail",
"personnel",
"pointer",
"poste",
"poste libre",
"posté (travail)",
"préavis (donner un)",#81
"prime",
"profession",
"promouvoir",
"qualification",
"qualifié",
"rappel de salaire",
"recherche d'emploi",
"recyclage",
"rémunération",
"renvoyer",
"reprendre le travail",
"retenue à la source",
"retraite",
"retraite anticipée",
"retraite (prendre sa)",
"retraité",
"revenu",
"risque du métier",
"salaire",
"salaire brut",
"salaire de début",
"salaire net",
"sécurité",
"spécialité (d'un travailleur)",
"stage",
"stagiaire",
"stressant",
"stressé",
"surmené",
"temps partiel",
"ticket de restaurant",
"travail (du)",
"travail (un)",
"travail au noir",
"travailleur",
"travailleur immigré",
"usine",
"vie active"
]



answers = [
    ["industrial injury","work injury"],
    ["job centre"],
    ["unemployement benefit"],
    ["according to seniority"],
    ["classified ads"],
    ["wage increase","wage rise"],
    ["promotion"],
    ["perks","fringe benefits"],
    ["on the floor"],
    ["odd jobs"],
    ["pay slip"],
    ["junior executive"],
    ["middle executive"],
    ["senior executive"], #14
    ["applicant","candidate"],
    ["application"],
    ["to apply for a job"],
    ["career"],
    ["personnel manager"],
    ["unemployment"],
    ["the unemployed"],
    ["leave","time off"],
    ["to be on leave"],
    ["maternity leave"],
    ["paid holiday","paid vacation","paid leave"],
    ["contract"],
    ["fixed-term contract"],
    ["foreman"],
    ["curriculum vitae","CV","résumé"],
    ["streamlining"],
    ["job seeker"],
    ["resignation"],
    ["qualifications","degrees","diplomas"],
    ["management"],
    ["to hire","to take on","to employ"],
    ["employment"],
    ["employee"],
    ["employer"],
    ["firm"],
    ["interview"],
    ["equal opportunity"],
    ["team","shift"],
    ["on probation"],
    ["vocational training"],#44
    ["on-the-job training"],
    ["to train"],
    ["to earn"],
    ["strike"],
    ["to go on strike"],
    ["striker"],
    ["overtime"],
    ["schedule"],
    ["allowance"],
    ["dole","unemployment benefit"],
    ["day off"],
    ["bank holiday","public holiday"],
    ["working day"],
    ["to be dismissed","to be fired","to be sacked"],
    ["dismissal"],
    ["redundancy"],
    ["labour force","workforce"],
    ["industrial disease"],
    ["mobility"],
    ["to bargain", "to negociate"],
    ["unskilled"],
    ["safety standard"],
    ["unskilled worker"],
    ["skilled worker"],
    ["semi-skilled worker"],
    ["involvement"],
    ["boss"],
    ["employers"],
    ["break"],
    ["pension"],
    ["work permit"],
    ["staff","personnel"],
    ["to clock in", "to clock out"],
    ["position","job","occupation"],
    ["vacancy"],
    ["shiftwork"],
    ["to give notice"],#81
    ["bonus","incentive"],
    ["occupation","profession"],
    ["to promote"],
    ["qualification"],
    ["skilled"],
    ["back pay"],
    ["job hunting"],
    ["retraining"],
    ["earnings"],
    ["to dismiss","to sack","to fire"],
    ["to resume work"],
    ["pay as you earn","PAYE"],
    ["retirement"],
    ["early retirement"],
    ["to retire"],
    ["pensioner"],
    ["earnings","income"],
    ["occupational hazard"],
    ["pay","salary","wage","wages"],#100
    ["gross wage"],
    ["initial salary", "commencing salary"],
    ["net salary"],
    ["safety"],
    ["line"],
    ["work experience","vocational training","internship"],
    ["trainee"],
    ["stressful"],
    ["stressed"],
    ["overworked"],
    ["part time"],
    ["restaurant voucher"],
    ["work"],
    ["job","occupation"],
    ["moonlighting"],
    ["worker"],
    ["migrant","guest worker"],
    ["factory","plant"],
    ["working life"]

]


userinput = ""
score = 0
tentatives = 0
print("jeancast pour arreter")
while (userinput != "jeancast"):
    i = random.randint(0,len(words))
    print(words[i])
    userinput = input()
    if userinput in answers[i]:
        print("en effet, " + words[i] + " : ",end="")
        for answer in answers[i]:
            print(answer,end=" ")
        print()
        score += 1
        tentatives += 1
    else:
        print("non, " + words[i] + " : ",end="")
        for answer in answers[i]:
            print(answer,end=" ")
        print()
        tentatives += 1

print("score:")
print(score)
print('nombre tentatives:')
print(tentatives)